name: Lighthouse Check
on: 
  push:
    branches: [main, Lighthouse_setup]
  pull_request:
    types: [opened]
    
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://insta-fontys.github.io/Frontend_Vue/register,https://insta-fontys.github.io/Frontend_Vue/login,https://insta-fontys.github.io/Frontend_Vue/home,https://insta-fontys.github.io/Frontend_Vue/buytokens,https://insta-fontys.github.io/Frontend_Vue/followers'
    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "70"
        minBestPracticesScore: "70"
        minPerformanceScore: "70"
        minProgressiveWebAppScore: "50"
        minSeoScore: "50"
